apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: calico-conf
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "flannel",
      "plugins": [
        {
          "type": "flannel",
          "name": "flannel.1",
          "delegate": {
            "isDefaultGateway": true,
            "hairpinMode": true
          }
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          }
        }
      ]
    }'